/**
 * Property-based tests for Mock Data Provider Service
 * 
 * **Validates: Requirements 4.4, 12.1, 12.2, 12.3, 12.4, 12.6**
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fc from 'fast-check';
import { mockDataProvider } from '../mockDataProvider';
import { getPropertyTestConfig } from '../../tests/propertyTestConfig';
import { Lead, Job, Technician } from '../types';

describe('MockDataProvider - Property Tests', () => {
  // Store original localStorage state
  let originalLocalStorage: Storage;

  beforeEach(() => {
    // Save original localStorage
    originalLocalStorage = { ...localStorage };
    // Clear localStorage before each test
    localStorage.clear();
  });

  afterEach(() => {
    // Restore original localStorage
    Object.keys(originalLocalStorage).forEach(key => {
      localStorage.setItem(key, originalLocalStorage[key]);
    });
  });

  describe('Property 12: Mock Data Provision', () => {
    it('should provide mock data when enabled and real data is empty', () => {
      /**
       * **Validates: Requirements 4.4**
       * 
       * For any empty data scenario, mock data should be provided when enabled
       */
      fc.assert(
        fc.property(
          fc.constantFrom('leads', 'jobs', 'technicians'),
          (dataType) => {
            // Enable mock data
            mockDataProvider.setEnabled(true);

            // Test with empty array
            const emptyData: any[] = [];
            const shouldUse = mockDataProvider.shouldUseMockData(emptyData);

            expect(shouldUse).toBe(true);

            // Test with null
            const shouldUseNull = mockDataProvider.shouldUseMockData(null as any);
            expect(shouldUseNull).toBe(true);

            // Test with undefined
            const shouldUseUndefined = mockDataProvider.shouldUseMockData(undefined as any);
            expect(shouldUseUndefined).toBe(true);

            // Disable mock data
            mockDataProvider.setEnabled(false);

            // Should not use mock data when disabled
            const shouldNotUse = mockDataProvider.shouldUseMockData(emptyData);
            expect(shouldNotUse).toBe(false);
          }
        ),
        getPropertyTestConfig('dev')
      );
    });

    it('should not provide mock data when real data exists', () => {
      /**
       * **Validates: Requirements 4.4**
       * 
       * For any non-empty data scenario, mock data should not be provided even when enabled
       */
      fc.assert(
        fc.property(
          fc.array(fc.anything(), { minLength: 1, maxLength: 10 }),
          (realData) => {
            // Enable mock data
            mockDataProvider.setEnabled(true);

            // Should not use mock data when real data exists
            const shouldUse = mockDataProvider.shouldUseMockData(realData);
            expect(shouldUse).toBe(false);
          }
        ),
        getPropertyTestConfig('dev')
      );
    });
  });

  describe('Property 33: Mock Data Structure - Leads', () => {
    it('should generate leads with all required fields and valid structure', () => {
      /**
       * **Validates: Requirements 12.2**
       * 
       * For any lead generated by the Mock_Data_Provider, it should contain all required fields:
       * id, name, email, phone, status, source, and created_at
       */
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 100 }),
          (count) => {
            const leads = mockDataProvider.generateLeads(count);

            // Should generate the correct number of leads
            expect(leads).toHaveLength(count);

            // Each lead should have all required fields with valid structure
            leads.forEach((lead: Lead) => {
              // Required fields exist
              expect(lead.id).toBeDefined();
              expect(lead.name).toBeDefined();
              expect(lead.email).toBeDefined();
              expect(lead.phone).toBeDefined();
              expect(lead.status).toBeDefined();
              expect(lead.source).toBeDefined();
              expect(lead.created_at).toBeDefined();

              // Field types are correct
              expect(typeof lead.id).toBe('string');
              expect(typeof lead.name).toBe('string');
              expect(typeof lead.email).toBe('string');
              expect(typeof lead.phone).toBe('string');
              expect(typeof lead.status).toBe('string');
              expect(typeof lead.source).toBe('string');
              expect(typeof lead.created_at).toBe('string');

              // ID is a valid UUID format
              expect(lead.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

              // Email has valid format
              expect(lead.email).toMatch(/^[^\s@]+@[^\s@]+\.[^\s@]+$/);

              // Status is one of the valid values
              expect(['new', 'contacted', 'qualified', 'converted']).toContain(lead.status);

              // Source is not empty
              expect(lead.source.length).toBeGreaterThan(0);

              // created_at is a valid ISO date string
              expect(() => new Date(lead.created_at)).not.toThrow();
              expect(new Date(lead.created_at).toISOString()).toBe(lead.created_at);

              // Name is not empty
              expect(lead.name.length).toBeGreaterThan(0);

              // Phone is not empty
              expect(lead.phone.length).toBeGreaterThan(0);
            });
          }
        ),
        getPropertyTestConfig('dev')
      );
    });
  });

  describe('Property 34: Mock Data Structure - Jobs', () => {
    it('should generate jobs with all required fields and valid structure', { timeout: 30000 }, () => {
      /**
       * **Validates: Requirements 12.3**
       * 
       * For any job generated by the Mock_Data_Provider, it should contain all required fields:
       * id, title, description, status, technician_id, lead_id, scheduled_date, and completion_date
       */
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 50 }),
          (count) => {
            const jobs = mockDataProvider.generateJobs(count);

            // Should generate the correct number of jobs
            expect(jobs).toHaveLength(count);

            // Each job should have all required fields with valid structure
            jobs.forEach((job: Job) => {
              // Required fields exist
              expect(job.id).toBeDefined();
              expect(job.title).toBeDefined();
              expect(job.description).toBeDefined();
              expect(job.status).toBeDefined();
              expect(job.lead_id).toBeDefined();
              expect(job.scheduled_date).toBeDefined();

              // Field types are correct
              expect(typeof job.id).toBe('string');
              expect(typeof job.title).toBe('string');
              expect(typeof job.description).toBe('string');
              expect(typeof job.status).toBe('string');
              expect(typeof job.lead_id).toBe('string');
              expect(typeof job.scheduled_date).toBe('string');

              // technician_id can be string or null
              if (job.technician_id !== null) {
                expect(typeof job.technician_id).toBe('string');
                // If technician_id exists, it should be a valid UUID
                expect(job.technician_id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
              }

              // completion_date can be string or null
              if (job.completion_date !== null) {
                expect(typeof job.completion_date).toBe('string');
                // If completion_date exists, it should be a valid ISO date
                expect(() => new Date(job.completion_date)).not.toThrow();
                expect(new Date(job.completion_date).toISOString()).toBe(job.completion_date);
              }

              // ID is a valid UUID format
              expect(job.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

              // lead_id is a valid UUID format
              expect(job.lead_id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

              // Status is one of the valid values
              expect(['pending', 'active', 'completed', 'cancelled']).toContain(job.status);

              // scheduled_date is a valid ISO date string
              expect(() => new Date(job.scheduled_date)).not.toThrow();
              expect(new Date(job.scheduled_date).toISOString()).toBe(job.scheduled_date);

              // Title is not empty
              expect(job.title.length).toBeGreaterThan(0);

              // Description is not empty
              expect(job.description.length).toBeGreaterThan(0);

              // Business logic: pending jobs should not have technician_id
              if (job.status === 'pending') {
                expect(job.technician_id).toBeNull();
              }

              // Business logic: completed jobs should have completion_date
              if (job.status === 'completed') {
                expect(job.completion_date).not.toBeNull();
              }
            });
          }
        ),
        getPropertyTestConfig('dev')
      );
    });
  });

  describe('Property 35: Mock Data Structure - Technicians', () => {
    it('should generate technicians with all required fields and valid structure', () => {
      /**
       * **Validates: Requirements 12.4**
       * 
       * For any technician generated by the Mock_Data_Provider, it should contain all required fields:
       * id, name, email, phone, skills, available, and rating
       */
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 100 }),
          (count) => {
            const technicians = mockDataProvider.generateTechnicians(count);

            // Should generate the correct number of technicians
            expect(technicians).toHaveLength(count);

            // Each technician should have all required fields with valid structure
            technicians.forEach((technician: Technician) => {
              // Required fields exist
              expect(technician.id).toBeDefined();
              expect(technician.name).toBeDefined();
              expect(technician.email).toBeDefined();
              expect(technician.phone).toBeDefined();
              expect(technician.skills).toBeDefined();
              expect(technician.available).toBeDefined();
              expect(technician.rating).toBeDefined();

              // Field types are correct
              expect(typeof technician.id).toBe('string');
              expect(typeof technician.name).toBe('string');
              expect(typeof technician.email).toBe('string');
              expect(typeof technician.phone).toBe('string');
              expect(Array.isArray(technician.skills)).toBe(true);
              expect(typeof technician.available).toBe('boolean');
              expect(typeof technician.rating).toBe('number');

              // ID is a valid UUID format
              expect(technician.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

              // Email has valid format
              expect(technician.email).toMatch(/^[^\s@]+@[^\s@]+\.[^\s@]+$/);

              // Name is not empty
              expect(technician.name.length).toBeGreaterThan(0);

              // Phone is not empty
              expect(technician.phone.length).toBeGreaterThan(0);

              // Skills array is not empty and contains strings
              expect(technician.skills.length).toBeGreaterThan(0);
              technician.skills.forEach(skill => {
                expect(typeof skill).toBe('string');
                expect(skill.length).toBeGreaterThan(0);
              });

              // Rating is within valid range (0-5)
              expect(technician.rating).toBeGreaterThanOrEqual(0);
              expect(technician.rating).toBeLessThanOrEqual(5);

              // Rating has at most 1 decimal place
              const decimalPlaces = (technician.rating.toString().split('.')[1] || '').length;
              expect(decimalPlaces).toBeLessThanOrEqual(1);
            });
          }
        ),
        getPropertyTestConfig('dev')
      );
    });
  });
});
